### ISSUE TITLE
Error: read.accession2taxid(list.files('.','accession2taxid.gz$'),'accessionTaxa.sql')

### ISSUE THREAD

**Issue by alizohaib7** [sherrillmix/taxonomizr#1]
Hi
Teacher 
Hope you are doing fine. I am trying to work with this package for the 1st time I am having following issue, that following the below mentioned command I am getting the error 

read.accession2taxid(list.files('.','accession2taxid.gz$'),'accessionTaxa.sql')

Reading nucl_est.accession2taxid.gz.
Reading nucl_gb.accession2taxid.gz.
Reading nucl_gss.accession2taxid.gz.
Reading nucl_wgs.accession2taxid.gz.
Reading in values. This may take a while.
Error: Problem creating sql file. Deleting.
Error in rsqlite_import_file(conn@ptr, name, value, sep, eol, skip) : 
  RS_sqlite_import: C:\Users\ALIZOH~1\AppData\Local\Temp\RtmpQx5v97\file926868d25ec2 line 238971807 expected 2 columns of data but found 3
In addition: Warning message:
In file.remove(sqlFile) :
  cannot remove file 'accessionTaxa.sql', reason 'Permission denied'

Your help to troubleshoot this problem is requested 
Regards 
Ali Zohaib

**Comment by sherrillmix** [comment]
The easiest explanation would be that one of your files is incomplete. Could you try running it on one file at a time and see if you get errors every time. You could do that manually or with something like:

    tmp<-tempfile()
    for(ii in list.files('.','accession2taxid.gz$')){
      message(ii)
      read.accession2taxid(list.files('.','accession2taxid.gz$'),tmp)
      file.remove(tmp)
    }

Thanks.

**Comment by alizohaib7** [comment]
Dear Sir
Thanks, the problem was (as you mentioned) incomplete download. I solved it by downloading the file manually and then putting it in my R folder and its working fine now. 

**Another Problem I am facing is with NC_ (accession numbers starting with NC) (NC, Complete genomic molecules)
 taxaId2<-accessionToTaxa(NC_010240.1,"accessionTaxa.sql")
Error in accessionToTaxa(NC_010240.1, "accessionTaxa.sql") : 
  object 'NC_010240.1' not found** 
How to fix that, Thanks in advance 


Sir,  How can we cite this package when we will be writing our paper. A special thanks for writing such an easy package, I have been searching for it and ended up learning python/linux but doing it in R is super easy. 

Regards 
Ali Zohaib

**Comment by sherrillmix** [comment]
I'm glad it worked out for you. Thanks for the bug report.

I've been meaning to try and get a simple publication (or maybe just an archived doi) for the package. Hopefully I'll have that set by the time you get close to publishing.

Good luck with the paper.
