### ISSUE TITLE
Error in result_create(conn@ptr, statement) :   no such table: ...

### ISSUE THREAD

**Issue by raerickson** [sherrillmix/taxonomizr#13]
I am trying to run code that worked on a co-workers machine. 

When I try to run

     taxa <- accessionToTaxa(arthropoda[ condor_index, 1], sqlFile= "accessionTaxa.sql")

I get the following error message

> Error in result_create(conn@ptr, statement) : 
  no such table: accessionTaxa
Timing stopped at: 0.031 0.003 0.036

A quick Google search found this question on [SO](https://stackoverflow.com/questions/44755802/sqldf-cant-find-the-data-with-error-no-such-table) and a comment one of the answers notes

> The problem is that RSQLite 2.0 was just released and does not work with older versions of sqldf. sqldf 0.4-11 which was just released should be used (or else use an older version of RSQLite)

I have tried upgrading taxonomizr and am using taxonomizr_0.5.3. Do you have any suggestions? Or has anyone else seen this with the package before?

**Comment by sherrillmix** [comment]
That could be something complex but I wonder if something went wrong when making the database. Could you try deleting `accessionTaxa.sql` and reinstalling with `prepareDatabase('accessionTaxa.sql')` (note that'll download some big files and take a while to process)?

**Comment by raerickson** [comment]
Thank you for the tip. There is some problem with how my machine was regenerating the sql database.  (My solution was to just use the sql database generated on my co-workers machine).
