### ISSUE TITLE
Function distance between taxons

### ISSUE THREAD

**Issue by mweberr** [sherrillmix/taxonomizr#16]
I was looking for a function that computes the distance between two taxons. Since I found nothing I would like to propose the following
```

  ## Load the Taxon Node Table from RSQLite into a data.frame
  db <- RSQLite::dbConnect(RSQLite::SQLite(), dbname=accessionSql)
  query <- paste0('SELECT id,parent,rank FROM nodes')
  taxaDF <- RSQLite::dbGetQuery(db,query)
  RSQLite::dbDisconnect(db)
  
  # Build IGraph object
  g <- graph_from_data_frame(taxaDF[,1:2],directed=FALSE)

  d <- distances(g, v = V(g)[name == fromId],to=V(g)[name == toId])
```

Is this distance calculation in the scope of taxonomizr ?

**Comment by sherrillmix** [comment]
This is an interesting use of graphs but what were you looking to accomplish with the distance? I worry that the NCBI taxonomy has a lot of intermediate level clades e.g. sub-family and super-genera that might make this a bit hard to interpret. If you wanted something similar with already existing functions then perhaps:

```
taxa<-getTaxonomy(c(9606,9913),'accessionTaxa.sql')
sum(is.na(condenseTaxa(taxa[1:2,])))
```

Although you'd want to think about what do with NAs there e.g. order Primates for Homo sapiens and order NA for Bos taurus.

**Comment by mweberr** [comment]
I am looking for a function to determine genes which underwent HGT (horizontal gene transfer). There is this very nice web-tool http://alienness.sophia.inra.fr  which is doing this for reference groups. In my case there is no reference group therefore I want to look within gene clusters.

My idea was to compare the distance between species in the taxonomic tree to check whether a distantly related species, carries a gene with high similarity to another clade. Do you know other approaches to score HGT for large sets of ortholog genes ?

**Comment by sherrillmix** [comment]
It does seem reasonable to compare the taxonomic distance between two species for that. I just worry that blindly parsing the node graph of NCBI taxonomy might not get you a very reliable distance. There's a lot of weirdness in there with the less common taxonomic ranks so a well studied clade might have something like:
Species - subGenus - Genus - superGenus - subFamily - Family 
so a distance of 10 if you're going down and back up the tree. (There's also some "no rank" divisions thrown in where ever useful too so can be even less structured than this.)

On the other hand, a less studied clade might just go:
species - genus - family
so a distance of 4. 

So for the same real "phylogenetic distance" of two species within a family, you can get very different distances if you simply count nodes.

As a first pass, you might just use the "common" taxonomic ranks. That's somewhat what the code above was doing. You'd also want to deal with NAs e.g. Bos taurus not having an "order" in the NCBI taxonomy.

**Comment by mweberr** [comment]
Thank your the discussion! Thinking about this idea to determine taxonomic distances, I am more and more clear that it is not very realistic. I did a bit research and came across an alignment-free distance calculator called MASH. Provided that we have the entire genome-sequence, this seems to be a good distance estimator https://github.com/marbl/Mash

**Comment by sherrillmix** [comment]
That seems pretty reasonable if the number of genomes isn't too large.
