### ISSUE TITLE
Error: with NC_ (accession numbers starting with NC)

### ISSUE THREAD

**Issue by alizohaib7** [sherrillmix/taxonomizr#2]
Dear Sir

It's working perfectly fine for all my records except for records starting with NC 

NC_ (accession numbers starting with NC)
taxaId2<-accessionToTaxa(NC_010240.1,"accessionTaxa.sql")
Error in accessionToTaxa(NC_010240.1, "accessionTaxa.sql") :
object 'NC_010240.1' not found

How can we fix it ? Your kind help in this regard is needed. Thanks. 

Regards 
Ali Zohaib

**Comment by sherrillmix** [comment]
Looks like you forgot to put quotes around the string. Try:

    taxaId2<-accessionToTaxa("NC_010240.1","accessionTaxa.sql")

**Comment by alizohaib7** [comment]
Hi
Sir Thank you so much for mentioning that, (however it was just an example), in reality I feed a list of accession numbers through csv file. For the 1st time I got  around 1% with NA results at all taxonomic levels, however running the same commands for the second time fixed the issue.  Thanks for your kind response sir, the issue is fixed now. 

Regards

**Comment by sherrillmix** [comment]
That's weird that you're getting different results with different runnings. Glad it worked out though. Let me know if it reoccurs.
