### ISSUE TITLE
Can't find nodes table?

### ISSUE THREAD

**Issue by aminards** [sherrillmix/taxonomizr#21]
I have installed the sqlLite database but when I run prepareDatabase to check it I see this odd note:

```
prepareDatabase('accessionTaxa.sql')
SQLite database accessionTaxa.sql already exists. Delete to regenerate
[1] "accessionTaxa.sql"
Warning message:
In file.remove(tmp) :
  cannot remove file 'C:\Users\MINARD~1\AppData\Local\Temp\RtmpGkhOfU\file13381f9165b0', reason 'Permission denied'
```

And when I try to run getTaxonomy I get an error that the nodes table is missing:

```
getTaxonomy(taxids, 'accessionTaxa.sql', desiredTaxa = c("superkingdom"))
Error: no such table: nodes
```

Where can I find the sqlIte database?  How can I fix this error?

I did set my working directory to the directory where I have my taxID tables on windows 10.

**Comment by aminards** [comment]
I restarted and this time didn't change my working directory.  Now it works correctly.  But for future reference, where is the accessionTaxa.sql so I might just put in the file path for it?

**Comment by sherrillmix** [comment]
If you don't specify a path then the .sql should go in whatever directory R is working in. You could set that ahead of time with `setwd('/some/path/')` (or specify the full path `prepareDatabase('/some/path/accessionTaxa.sql')`) or you can figure out where R's current working directory is with `getwd()`.
