### ISSUE TITLE
Error in connection_import_file(conn@ptr, name, value, sep, eol, skip) :    RS_sqlite_import: disk I/O error Error: no such savepoint: dbWriteTable

### ISSUE THREAD

**Issue by wjj666** [sherrillmix/taxonomizr#22]
Dear Sherrillmix,
There is one issue when I run prepareDatabase('accessionTaxa.sql'). Could you please tell me how to fix it? Thank you very much.

> library(taxonomizr)
> prepareDatabase('accessionTaxa.sql')
Downloading names and nodes with getNamesAndNodes()
./names.dmp, ./nodes.dmp already exist. Delete to redownload
Downloading accession2taxid with getAccession2taxid()
This can be a big (several gigabytes) download. Please be patient and use a fast connection.
./nucl_gb.accession2taxid.gz, ./nucl_wgs.accession2taxid.gz already exist. Delete to redownload
Preprocessing names with read.names.sql()
Preprocessing nodes with read.nodes.sql()
Preprocessing accession2taxid with read.accession2taxid()
Reading ./nucl_gb.accession2taxid.gz.
Reading ./nucl_wgs.accession2taxid.gz.
Reading in values. This may take a while.
Error in connection_import_file(conn@ptr, name, value, sep, eol, skip) : 
  RS_sqlite_import: disk I/O error
Error: no such savepoint: dbWriteTable

**Comment by sherrillmix** [comment]
This sounds similar to Issue #5 and so might be fixed by starting R with TMPDIR=/path/to/tmp R then running commands as usual.

**Comment by sherrillmix** [comment]
Sounds like a problem writing files. Maybe check

**Comment by sherrillmix** [comment]
Sorry misclicked and closed unintentionally.
