### ISSUE TITLE
Error in utils::download.file(url, tarFile, mode = "wb") : cannot open URL 'ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz'

### ISSUE THREAD

**Issue by jliu-nj** [sherrillmix/taxonomizr#23]
Hi, Thank you for this R package. I installed it and tried to run prepareDatabase('accessionTaxa.sql'). But got this error. I ran this on our serve interactive R.

> prepareDatabase('accessionTaxa.sql')
Downloading names and nodes with getNamesAndNodes()
trying URL 'ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz'
URL 'ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz': status was 'Couldn't resolve host name'Error in utils::download.file(url, tarFile, mode = "wb") : 
  cannot open URL 'ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz'

I checked the URL  'ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz'. I can downloaded it with wget, and the size is ~50M.

Is there any reason for its failure in downloading in R?

Thank you.

**Comment by sherrillmix** [comment]
Hmm. It seems to be working here:

```
> taxonomizr::prepareDatabase('accessionTaxa.sql')
Downloading names and nodes with getNamesAndNodes()
trying URL 'ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz'
Content type 'unknown' length 54055484 bytes (51.6 MB)
==================================================
...
```

NCBI seems to have occasional networking difficulties. I know you already double checked with wget but could you repeat the R command again to check if there was some sort of blip? 

Failing that could you post the results of `sessionInfo()` to start narrowing down what could be causing an issue.
