### ISSUE TITLE
read.accession not working; preparedatabase failed

### ISSUE THREAD

**Issue by lcamVz** [sherrillmix/taxonomizr#28]
I've been trying to get the databases to download and get the taxonomy working. 

lastly I got this error. 

Reading NCBI_DATABASE/nucl_gb.accession2taxid.gz.
Error in readBin(inn, what = raw(0L), size = 1L, n = BFR.SIZE) : 
  error reading from the connection
In addition: Warning message:
In readBin(inn, what = raw(0L), size = 1L, n = BFR.SIZE) :
  invalid or incomplete compressed data
> packageVersion('taxonomizr')
[1] ‘0.6.0’

**Comment by sherrillmix** [comment]
A bit more output might be useful for debugging but that sounds like it may be a download problem. Could you redownload `NCBI_DATABASE/nucl_gb.accession2taxid.gz` and/or check to see that its filesize is close to the expected 8263483 KB or that its md5 matches:
 ftp://ftp.ncbi.nih.gov/pub/taxonomy/accession2taxid/nucl_gb.accession2taxid.gz.md5

**Comment by lcamVz** [comment]
Thank you for the quick reply. 

 I manually download them from the ftp and it worked I used wget -i list.txt  to get all of the nucleic and protein.

**Comment by sherrillmix** [comment]
That's good it ended up working for you. The package has had a few hard to replicate reports of download problems lately e.g. #27. Not sure what's causing them but I think when I get a chance I'll add an automatic md5 check after the download to at least catch when they happen. Thanks for the bug report.
