### ISSUE TITLE
Error in accesion to taxa

### ISSUE THREAD

**Issue by lcamVz** [sherrillmix/taxonomizr#29]
When running `accessionToTaxa` I get. 

`Warning messages:
1: In file.remove(tmp) :
  cannot remove file 'C:\Users\micro\AppData\Local\Temp\RtmpQT7MmR\filebbc2ec6fc4280c', reason 'Permission denied'
2: In file.remove(tmp) :`

I am in a windows PC.

**Comment by sherrillmix** [comment]
That looks like R can create files in Temp but not delete them. I guess some Windows craziness but shouldn't particularly matter other than leaving leftover temporary files in your Temp folder (assuming no other errors). You might want to delete that file manually once everything is processed to avoid wasting hard drive space (usually R cleans up anyway when you close it but might be something funny here).

**Comment by lcamVz** [comment]
It is weird. Thank you for the reply I got everything to run! I just delete the tmps like you mention.

**Comment by sherrillmix** [comment]
Great. Glad it worked for you. Let me know if you have any other trouble.
