### ISSUE TITLE
All taxonomic levels

### ISSUE THREAD

**Issue by dleopold** [sherrillmix/taxonomizr#30]
Is it possible to retrieve all taxonomic levels for a given id without knowing them ahead of time? An issue I am running into is multiple taxonomic levels being assigned to "clade". For example, looking up the full lineage for taxid 2511165 on NCBI shows:

`cellular organisms; Eukaryota; **Sar**; **Stramenopiles**; **Ochrophyta**; Eustigmatophyceae; Eustigmatales; Monodopsidaceae; Microchloropsis`

and all 3 bold levels above are identified as "clade".   Including "clade" one or more times in `desiredTaxa=` only returns the first level assigned to clade. 

```
> getTaxonomy(2511165,"/mnt/efs/JV_taxonomy/NCBI_accessionTaxa_20210211.sql", desiredTaxa = c("superkingdom", "phylum", "clade", "clade", "clade", "class", "order", "family", "genus", "species"))
        superkingdom phylum clade clade clade class               order           family            genus            
2511165 "Eukaryota"  NA     "Sar" NA    NA    "Eustigmatophyceae" "Eustigmatales" "Monodopsidaceae" "Microchloropsis"
        species                 
2511165 "Microchloropsis salina"
```

**Comment by sherrillmix** [comment]
3 clades in a row. Things are never simple with taxonomy.

I think I can throw in a modified function that just gives you all the taxonomy for a given taxa and then it would be up to the user deal with making sense of it. That seems like it would be good for debugging or building off. I'll poke at it now.

**Comment by sherrillmix** [comment]
I just added a function to the github version of the packages (can install with `devtools::install_github('sherrillmix/taxonomizr')`) to allow pulling the full taxonomy e.g.:

```
getRawTaxonomy(2511165,'accessionTaxa.sql')
$`2511165`
                 species                    genus                   family 
"Microchloropsis salina"        "Microchloropsis"        "Monodopsidaceae" 
                   order                    class                    clade 
         "Eustigmatales"      "Eustigmatophyceae"             "Ochrophyta" 
                 clade.1                  clade.2             superkingdom 
         "Stramenopiles"                    "Sar"              "Eukaryota" 
                 no rank 
    "cellular organisms" 
 ```

Does that do what you were looking for?

**Comment by dleopold** [comment]
That does it. Thanks!
