### ISSUE TITLE
getAccession2taxid(types='prot') download old files

### ISSUE THREAD

**Issue by ZexuanZhao** [sherrillmix/taxonomizr#35]
Hi,

It seems that `getAccession2taxid(types='prot')` is going to download the prot.accession2taxid.gz file instead of prot.accession2taxid.FULL.gz  file on [database](https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/), which is just 47 kb. It might be due to change in the database.

<img width="580" alt="Screen Shot 2021-10-25 at 9 15 41 AM" src="https://user-images.githubusercontent.com/37946201/138702306-1a5da4d9-6b82-4de6-bf75-1deb95c5eac3.png">

**Comment by sherrillmix** [comment]
Hmm it does indeed look like they changed the databases. The README seems to indicate prot.accession2taxid.gz should still be valid:

> prot.accession2taxid.gz
> TaxID mapping for live protein sequence records which have GI identifiers.
> 
> prot.accession2taxid.FULL.gz
> TaxID mapping for all live protein sequence records, including GI-less WGS proteins
> 
> prot.accession2taxid.FULL.NN.gz
> TaxID mapping for all live protein sequence records, split into smaller files containing 400 million rows each.

But it certainly does seem to be an empty file at the moment. I wonder if that is a permanent change or just something that got messed up in the most recent update (appears the file was updated ~9 hours ago).

Did you run into this issue yesterday or earlier (i.e. in previous versions of the database)?

**Comment by ZexuanZhao** [comment]
I just came across this issue. 


> Did you run into this issue yesterday or earlier (i.e. in previous versions of the database)?

**Comment by sherrillmix** [comment]
Hmm I haven't been keeping an eye on it but it looks like the non-FULL file was still valid in March at least:
http://web.archive.org/web/20210324124216/http://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/
I'm thinking I might give it a day or two and see if they bring it back before switching to the larger FULL file. 

Or is this holding up your research? I could add an option to feed in the exact file name directly. Alternatively you could download manually and then just continue using the already downloaded file.

**Comment by ZexuanZhao** [comment]
@sherrillmix Thank you very much. The archive data is helpful. I can adjust them by myself. Thank you.

**Comment by sherrillmix** [comment]
It seems the prot.accession2taxid.gz is back to a real 6.6 Gb file as of Nov 1, 2021:
![Screenshot 2021-11-01 at 12-11-16 Index of pub taxonomy accession2taxid](https://user-images.githubusercontent.com/1217152/139703858-2efd0d38-85e7-4183-8f03-c436e650affa.png)

I guess the empty file was just a NCBI hiccup. For my future reference, it looks like they probably update the database every Monday.

Thanks for reporting. I'll close for now but definitely let me know if you run into any other problems.
