### ISSUE TITLE
I can't match the accession number with taxa ID

### ISSUE THREAD

**Issue by vini8cs** [sherrillmix/taxonomizr#37]
I'm trying to get the accession number using this taxa ID from NCBI, but it's returning NAs:

blastAccessions <- c("WP_145099348.1", "WP_084254954.1","WP_214290166.1")
ids<-accessionToTaxa(blastAccessions,"accessionTaxa.sql")

What could be happening? I've seen other issue topics, but I couldn't find the solution.

**Comment by sherrillmix** [comment]
Can you provide the larger context e.g. how you created accessionTaxa.sql? For example, I see those are protein IDs and the default is to just download the nucleotide ID databases.

**Comment by vini8cs** [comment]
I created the the accessionTaxa.sql using prepareDatabase('accessionTaxa.sql'), but you're right, I'm using protein data and the accession2taxid files are for nucleotide data. I didn't realized it. However, I was able to get the taxonomic data using the function getId() with the species names. So, thank you!

**Comment by sherrillmix** [comment]
Great. I debated whether to include the protein IDs by default but they do add a decent chunk to an already big download/database so have been leaving them optional. Good luck with your research.

**Comment by vini8cs** [comment]
Thank you very much!

**Comment by sherrillmix** [comment]
Just in case anyone ends up here later, if you want the protein data then you'd want to do:
`prepareDatabase('accessionTaxaProt.sql',types='prot')`
for proteins.
