### ISSUE TITLE
accession2taxid ftp

### ISSUE THREAD

**Issue by mweberr** [sherrillmix/taxonomizr#38]
Hi,
I realise there have been a couple of other issues recently downloading files from ftp such as nucl_gb.accession2taxid.gz. Now there is a mismatch with the MD5 checkum and prepareDatabase stops. My question: How can I build an accessionsql database with only nodes and names table to run the function getTaxonomy ? Is this possible to just skip accession2taxid ?

Best, Michael

**Comment by sherrillmix** [comment]
The md5 doesn't match the actual download now? Great. I'm downloading now to double check. But yes there is an option to just get the names and nodes `prepareDatabase(getAccessions=FALSE)` e.g.:

```
> prepareDatabase(getAccessions=FALSE)
Downloading names and nodes with getNamesAndNodes()
 [100%] Downloaded 57373562 bytes...
 [100%] Downloaded 49 bytes...
Preprocessing names with read.names.sql()
Preprocessing nodes with read.nodes.sql()
[1] "nameNode.sqlite"

> getTaxonomy(9602,'nameNode.sqlite')
     superkingdom phylum     class      order      family      genus  
9602 "Eukaryota"  "Chordata" "Mammalia" "Primates" "Hominidae" "Pongo"
     species         
9602 "Pongo pygmaeus"
```

**Comment by sherrillmix** [comment]
Hmm it looks like the downloaded file and the reported md5 currently match (updated on 2022-02-21 03:02):

```
> cat *.md5
41d1235eca4d1148df6101110e80c6d8  nucl_gb.accession2taxid.gz
656cfb129434df2312abb5cfe2ef08d2  nucl_wgs.accession2taxid.gz

>md5sum *.gz
41d1235eca4d1148df6101110e80c6d8  nucl_gb.accession2taxid.gz
656cfb129434df2312abb5cfe2ef08d2  nucl_wgs.accession2taxid.gz
```

Were you seeing something different? If so, perhaps it has been fixed in the meantime?

**Comment by mweberr** [comment]
Yes it is fixed. Thanks for the hint with the parameter getAccession, very helpful!

**Comment by sherrillmix** [comment]
Great! Glad it worked out. Thanks for the bug report on mixed up md5s. Definitely good to keep that in mind for a cause for future problems. Good luck with your research.
