### ISSUE TITLE
read.names failing to read in names.dmp table

### ISSUE THREAD

**Issue by afkoeppel** [sherrillmix/taxonomizr#4]
I can read in the nodes.dmp file just fine, but names.dmp fails. The error suggests that read.names is expecting a different number of columns than are present in names.dmp.  

Looking at the function it seems the problem comes in when removing columns 3 & 4 from the splitLines object.  The colnames command expects there to be two columns remaining, but there are three (names.dmp has five columns).

I was able to work around this by editing the read.names function, so that it removes the fifth column as well.
splitLines <- splitLines[, -(3:5)]

That seems to have corrected the problem for me, but I thought you might want to be aware of it.

library(taxonomizr)
getNamesAndNodes()
getAccession2taxid()
read.accession2taxid(list.files('.','accession2taxid.gz$'),'accessionTaxa.sql')
taxaNodes<-read.nodes('nodes.dmp')
taxaNames<-read.names('names.dmp')
Error in `colnames<-`(`*tmp*`, value = c("id", "name")) : 
  length of 'dimnames' [2] not equal to array extent
In addition: Warning message:
In (function (..., deparse.level = 1)  :
  number of columns of result is not a multiple of vector length (arg 1)

read.names <- function (nameFile, onlyScientific = TRUE) 
{
  splitLines <- do.call(rbind, strsplit(readLines(nameFile), 
                                        "\\s*\\|\\s*"))
  if (onlyScientific) 
    splitLines <- splitLines[splitLines[, 4] == "scientific name", 
                             ]
  splitLines <- splitLines[, -(3:5)]
  colnames(splitLines) <- c("id", "name")
  splitLines <- data.frame(id = as.numeric(splitLines[, "id"]), 
                           name = splitLines[, "name"], stringsAsFactors = FALSE)
  out <- data.table::data.table(splitLines, key = "id")
  data.table::setindex(out, "name")
  return(out)
}
taxaNames<-read.names('names.dmp')
# I still get a warning, but the function now works

**Comment by sherrillmix** [comment]
It looks like NCBI just updated their taxonomy files and that names.dmp now contains a single entry on the 2647315th row with an extra "|" character in it:
2068995\t|\tSmeringopina bwiti Huber, 2013 |\t|\t\t|\tauthority\t|
Note the " |" after species name. I guess that's a typo but I don't want to go overriding NCBI so I'll have to call that a species name of "Smeringopina bwiti Huber, 2013 |".  

I've updated the regex splitting the rows to account for this "unusual" species name. The current github version should work correctly. You should be able to install it with `devtools::install_github('sherrillmix/taxonomizr')`.

Let me know if that fixes things.

**Comment by afkoeppel** [comment]
That fixed the problem for me.  Thanks.

**Comment by sherrillmix** [comment]
Great. Thanks for the bug report.
