### ISSUE TITLE
Kingdom bacteria only

### ISSUE THREAD

**Issue by mweberr** [sherrillmix/taxonomizr#40]
Hi,

I recently found a duplicate taxon ID for genus Leptothrix, which is a genus name for bacterial species as well as for Leptothrix hardyi, a spider species. Spiders are interesting species, but I need take care of the bacteria at the moment.

Would it be possible to tell function getId to only search in a particular kingdom, such as Bacteria ?

Best, Michael

**Comment by sherrillmix** [comment]
For a reproducible example, I think that's:
```
lepto<-getId('Leptothrix','accessionTaxa.sql')
print(lepto)
```
producing:
```
[1] "88,1907117"
Warning message:
In taxonomizr::getId("Leptothrix", "accessionTaxa.sql") :
  Multiple taxa ids found for Leptothrix. Collapsing with commas
```

I guess I would do:
```
onlyBacteria<-function(xx)xx[getTaxonomy(xx,desiredTaxa='superkingdom')=='Bacteria']
lapply(strsplit(lepto,','),onlyBacteria)
```
producing:
```
[[1]]
[1] "88"
```
Indicating that only taxa 88 is within bacteria.

For a slightly more complex example:
```
taxaNames<-c('Leptothrix','Homo sapiens','Escherichia coli')
ids<-getId(taxaNames,'accessionTaxa.sql')]
bacteriaIds<-lapply(strsplit(ids,','),onlyBacteria)
print(bacteriaIds)
```
producing:
```
[[1]]
[1] "88"

[[2]]
character(0)

[[3]]
[1] "562"
```

You'll want to do something like:
```
sapply(bacteriaIds,length)
```
and deal with any cases with 0 (probably non-bacteria) or >1 (multiple ambiguous bacterial clades) entries remaining.

Is that what you were looking for?

**Comment by mweberr** [comment]
Great! Thank you for helpful code to extract the bacteria kingdom!
