### ISSUE TITLE
Disk is full (and moving tmp location doesn't solve it)

### ISSUE THREAD

**Issue by Aron-github** [sherrillmix/taxonomizr#41]
Hello there,

I'm running this super small snippet of code:
```
unixtools::set.tempdir("/tmpdata/mytmp")

# install.packages("taxonomizr")
devtools::install_github('sherrillmix/taxonomizr')
library(taxonomizr)

prepareDatabase(
  sqlFile = "accessionTaxa.sqlite",
  tmpDir = "/tmpdata/mytmp",
  vocal = TRUE)
```
and with both the cran installation and the github one, I hit the same error:

```
Downloading names and nodes with getNamesAndNodes()
 [100%] Downloaded 58237570 bytes...
 [100%] Downloaded 49 bytes...
Preprocessing names with read.names.sql()
Preprocessing nodes with read.nodes.sql()
Downloading accession2taxid with getAccession2taxid()
This can be a big (several gigabytes) download. Please be patient and use a fast connection.
 [100%] Downloaded 2193408674 bytes...
 [100%] Downloaded 61 bytes...
 [100%] Downloaded 3892554970 bytes...
 [100%] Downloaded 62 bytes...
Preprocessing accession2taxid with read.accession2taxid()
Reading /tmpdata/mytmp/nucl_gb.accession2taxid.gz.
Reading /tmpdata/mytmp/nucl_wgs.accession2taxid.gz.
Preprocessing nodes with read.nodes.sql()
Downloading accession2taxid with getAccession2taxid()
This can be a big (several gigabytes) download. Please be patient and use a fast connection.
 [100%] Downloaded 2193408674 bytes...
 [100%] Downloaded 61 bytes...
 [100%] Downloaded 3892554970 bytes...
 [100%] Downloaded 62 bytes...
Preprocessing accession2taxid with read.accession2taxid()
Reading /tmpdata/mytmp/nucl_gb.accession2taxid.gz.
Reading /tmpdata/mytmp/nucl_wgs.accession2taxid.gz.
Reading in values. This may take a while.
Adding index. This may also take a while.
Error: database or disk is full
```

As previously reported, I changed the tmp folder to be one where I know I have a lot of free space, and still I'm getting the same error. Also what reported in #5 (i.e. using system call to set TMPDIR and run the command) didn't work for me.

Please find attached the `sessionInfo()` output
[20220531_sessionInfo.txt](https://github.com/sherrillmix/taxonomizr/files/8805287/20220531_sessionInfo.txt)
.

**Comment by sherrillmix** [comment]
I notice that the final accessionTaxa.sqlite is still being written to the local directory. Does that directory have ~70Gb of space for the final database?

**Comment by Aron-github** [comment]
There should more than 1 Tb avail on the disk I'm writing to...

**Comment by sherrillmix** [comment]
Hmm that should be enough space but you do appear to be running out of space somewhere. Maybe `getwd` to make sure your working directory is in the right place and `system('df -h .')` to make sure you have enough space there? 

Also the link to issue #5 displays the correct url (`github.com/sherrillmix/taxonomizr/issues/5`) but actually links to an incorrect page in case anyone else comes across this.

**Comment by Aron-github** [comment]
Unfortunately `getwd` and `system('df -h')` return exactly what I knew already, i.e. that I'm working in the desired folder which has 1.4T of free space. Any other suggestion?

Also, sorry for mistakenly referring to the issue #5 via url, it is now corrected in the first post.

**Comment by sherrillmix** [comment]
Hmm that's pretty odd. I guess if it's not the final directory then it's something related to the temp directory. That can be tricky with SQLite. You said you started R with something like `TMPDIR=/path/to/tmp R` (note the variable assignment is in the same input as `R`) correct? Maybe double check that that stuck with `system('echo $TMPDIR')` and `system('df -h "$TMPDIR"')`?

**Comment by Aron-github** [comment]
In both cases I am getting back what I wrote you above BUT I'm running the code within RStudio, that's why, as written in the first post, I set the TMPDIR both in my .Renviron and manually in the script via `unixtools::set.tempdir`...

**Comment by sherrillmix** [comment]
unixtools::set.tempdir doesn't appear to set the TMPDIR variable so that's most likely not going to help SQLite use the correct directory. Setting it in .Renviron should set TMPDIR correctly but looking back at the previous issue #5, it actually ended with a report from the user that that in fact did not cover all their uses with no followup. So it seems setting TMPDIR may not always solve the issue. I guess either there are some systems where SQlite doesn't listen to TMPDIR or RStudio is doing something funny. I don't have RStudio to debug so I guess my advice would still be:

> The package is using sqlite for the database and sqlite3 can be a bit finicky with /tmp problems so I would guess that's the cause. I think it does not listen to R's internal environment variables but would listen to a TMPDIR set prior to starting R. If you start R with TMPDIR=/path/to/tmp R and rerun things is the database created correctly? If you wanted to keep everything internal to RStudio then I suppose you could do a system call within RStudio with something like.:
system('TMPDIR=/path/to/tmp R -e "taxonomizr::prepareDatabase(\'accessionTaxa.sql\')"')

**Comment by sherrillmix** [comment]
This [stackoverflow answer](https://stackoverflow.com/a/45092059) suggests that the variable needs to be set in Renviron.site and not .Renviron. I haven't really mucked around in startup but apparently Renviron.site is more global than .Renviron as per this [stackoverflow](https://stackoverflow.com/a/51254606) and ?Startup so perhaps reasonable. 

Another option might be `prepareDatabase(extraSqlCommand="PRAGMA temp_store_directory = '/MY/TMP/DIR'")` although I haven't had a chance to test that recently.

**Comment by sherrillmix** [comment]
`prepareDatabase(extraSqlCommand="PRAGMA temp_store_directory = '/MY/TMP/DIR'")` seems to work for me. SQLite deletes the temporary file as soon as it creates it so the temp file isn't visible by `ls` but I can see the space being used in the correct partition while it prepares the indexing. Maybe give that a shot and let me know if it fixes things. If that works, I'm debating just setting the function to call that PRAGMA automatically at the location defined in the `tmpDir` argument to `prepareDatabase` so people can stop worrying about this.

**Comment by Sanrrone** [comment]
same here, it is needed a new flag for tmp. the `extraSqlCommand="PRAGMA temp_store_directory = '/MY/TMP/DIR'"` doesn't work Neither change the ENV TMPDIR.
what it worked was modify the Renviron.site file in /etc/R.
