### ISSUE TITLE
get taxID for a huge list of accesion numbers

### ISSUE THREAD

**Issue by sumitra20** [sherrillmix/taxonomizr#43]
Hi,

I have .csv file with a huge list of accession numbers (thousands) which i would like find the taxonomic IDs for. Is there a way to edit the code below in order to include the entire list of accession numbers from my csv file? 

taxaId<-accessionToTaxa(c("WP_227648936.1","KAF2914273.1"),"accessionTaxa.sql")

help is much appreciated, thank you.

**Comment by sherrillmix** [comment]
That's more of a basic R question but you'd probably want to read in the .csv:

```
myCsv<-read.csv('PATH/TO/THE.CSV')
```

and then call the same function on the column of the csv containing your accession numbers either by number e.g. if they were in the first column:

```
taxaId<-accessionToTaxa(myCsv[,1],"accessionTaxa.sql")
```

or by name e.g. if row 1 of your column of interest was "ID" then:

```
taxaId<-accessionToTaxa(myCsv[,'ID'],"accessionTaxa.sql")
```
