### ISSUE TITLE
FR: set a variable with default path for the databases

### ISSUE THREAD

**Issue by splaisan** [sherrillmix/taxonomizr#47]
I now run each taxonomizr session in the same folder where I created the DB which is not ideal for multiple projects and would prefer that the package looks for the database in a defined folder (/data/.../taxonomizrDB) while the working data is in another place (project folder)

Can we do this now and if not could it be added?

Thanks

**Comment by splaisan** [comment]
would, by any chance, this be a solution?

## in bash (in some .rc file)

`export taxonomizrDB=/path/to/taxonomizrDB`

## in R

```
dbPath=Sys.getenv("taxonomizrDB")
prepareDatabase(tmpDir = dbPath)
... more commands ...
```

**Comment by sherrillmix** [comment]
I may not be fully catching but does't including a path in the  `sqlFile` argument of the various commands satisfy this? e.g. `prepareDatabase("/path/to/taxonomizrDB/dbName.sql")` and `getTaxonomy(ids,"/path/to/taxonomizrDB/dbName.sql")`

**Comment by splaisan** [comment]
probably yes, thanks for your answer, I try this

**Comment by sherrillmix** [comment]
Great. Good luck in your research.

**Comment by splaisan** [comment]
it works, thanks a lot for the great tool!
