### ISSUE TITLE
Assignment of taxonomy to blast hits

### ISSUE THREAD

**Issue by simang5c** [sherrillmix/taxonomizr#49]
Hi, I have some blast hit and i am attaching the blast hit ids, query and ouptut below. 

taxaId<-accessionToTaxa(c("SJL08569.1","PBK92452.1"),"../../accessionTaxa.sql")
print(taxaId)
[1] NA NA

May I know what could be the issue?

**Comment by sherrillmix** [comment]
Looks like protein sequences. NCBI stores those in a separate `prot.accession2taxid.gz` which is pretty big so not downloaded by default. To make a database with proteins do something like:

```
prepareDatabase(types='prot')
```

or `types=c("nucl_gb", "nucl_wgs","prot")` for proteins and nucleotides.

Once that's done they seem to annotate fine:

```
taxonomizr::accessionToTaxa(c("SJL08569.1","PBK92452.1"),"accessionTaxa.sql")
[1] 47428 47427
```
