### ISSUE TITLE
error: no such column: tmp.query.accession

### ISSUE THREAD

**Issue by ewelinarubin** [sherrillmix/taxonomizr#50]
Hi - I am trying to execute the following script: 
```
library(taxonomizr)
prepareDatabase('accessionTaxa.sql')
acctoget<- read.table("acctoget.txt",header=FALSE)
taxaId<-accessionToTaxa(acctoget,"accessionTaxa.sql")
taxa <- getTaxonomy(taxaId,taxaNodes,taxaNames) 
write.table(taxa,"taxa.txt",sep="\t",row.names=FALSE)
```
The sql. data looks correct 
I see the following: 

```
[100%] Downloaded 62 bytes...
Preprocessing accession2taxid with read.accession2taxid()
Reading ./nucl_gb.accession2taxid.gz.
Reading ./nucl_wgs.accession2taxid.gz.
Reading in values. This may take a while.
Adding index. This may also take a while.
[1] "accessionTaxa.sql"
```
Attached is my file with accession numbers: 

[acctoget.txt](https://github.com/sherrillmix/taxonomizr/files/9983343/acctoget.txt)

What am I doing wrong?

**Comment by sherrillmix** [comment]
`accessionToTaxa` expects a vector not an entire data.frame so something like `accessionToTaxa(acctoget[,1],"accessionTaxa.sql")` should work.

Your next problem will probably be that a decent proportion of those appear to be protein IDs so you'd probably want the prot database:

```
prepareDatabase(types='prot')
```

Your next problem will be that the call to getTaxonomy should be something like:
```
getTaxonomy(taxaId,'accessionTaxa.sql')
```
