### ISSUE TITLE
Questions for the issue of taxonomizr package being terminated during operation

### ISSUE THREAD

**Issue by kejsh1320** [sherrillmix/taxonomizr#54]
Thanks to the author for the advice. Considering that the hard drive space of the laptop is insufficient, I ran this R package on the Linux server, the commands and errors are as follows:
> library(taxonomizr)
> prepareDatabase('accessionTaxa.sql')
Downloading names and nodes with getNamesAndNodes()
 [100%] Downloaded 60165298 bytes...
 [100%] Downloaded 49 bytes...
Preprocessing names with read.names.sql()
[1]    3838773 terminated  R

At first I thought it might be due to insufficient memory running on the server, so I switched to a larger memory manager to run the taxonomizr package, and this problem was well solved. Hopefully it‘s helpful to anyone else having similar problems.

**Comment by sherrillmix** [comment]
Thanks for the bug report. That is pretty strange. Maybe a very tight memory limit or some library call that was causing the OS to freak out? I'm glad it worked out and let me know if anything similar pops up again.
