### ISSUE TITLE
Error in downloading database using prepareDatabase

### ISSUE THREAD

**Issue by sxh1136** [sherrillmix/taxonomizr#57]
Hi there, 
Running prepareDatabase('accessionTaxa.sql') returns this:
`Downloading names and nodes with getNamesAndNodes()
Download status: 1 done; 0 in progress. Total size: 57.70 Mb (100%)... done!             
Error in (function (outDir = ".", url = sprintf("%s://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz",  : 
  Downloaded file does not match ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz File corrupted or download ended early?`

The download also breaks during the middle of the installation but I assume thats a NCBI issue and resuming the download seems to work fine, It seems like a similar issue to #51. If there's an older version of the db you can send me I'd appreciate it (if the fix isn't easy ofc)!

**Comment by sherrillmix** [comment]
#51 seems unlikely to be related. That appeared to be due to some permission issue on the user side although the user never followed up. 

Here the function is reporting that the taxdump.tar.gz file was not downloaded correctly. Could be a desynchronization on the NCBI side between their md5 checksum and the actual file or some error in the `taxonomizr` code but I guess the more likely is a random blip in the internet. I would repeat a couple times to make sure the error is replicable. 

For example, I was just able to download the taxdump.tar.gz file correctly using the `prepareDatabase` function so if there was any funny business going on, it doesn't seem to be occurring now on my end at least. I do see that taxdump.tar.gz was last modified 2023-02-21 08:28 (EST maybe?) so if you were downloading around then then it's possible you got unlucky and downloaded the old version of the database and the new version of the md5 checksum. If so, again a repeat download would fix this.

This does suggest that it'd be good to add a bit more error reporting to the functions. Perhaps output the checksums and modification dates of the files. I'll put that on the todo list.

**Comment by sxh1136** [comment]
I've tried several more times over the last couple hours to not avail. I wonder if it has something to do with the download stopping 3-5 times before getting to 100%?

`> prepareDatabase('accessionTaxa.sql')
Downloading names and nodes with getNamesAndNodes()
Download status: 1 done; 0 in progress. Total size: 57.70 Mb (100%)... done!             
Error in resumableDownload(url, tarFile, quiet = FALSE) : 
  Download failed with error: "server did not report OK, got 450". Progress is saved in C:\Users\siufu\AppData\Local\Temp\Rtmpmw218d/taxdump.tar.gz.__TMP__ and continued download can be attempted by repeating the previous command.
Delete C:\Users\siufu\AppData\Local\Temp\Rtmpmw218d/taxdump.tar.gz.__TMP__ or set resume=FALSE to start from scratch.`
`> prepareDatabase('accessionTaxa.sql')
Downloading names and nodes with getNamesAndNodes()
Download status: 1 done; 0 in progress. Total size: 57.70 Mb (100%)... done!             
Error in (function (outDir = ".", url = sprintf("%s://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz",  : 
  Downloaded file does not match ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz File corrupted or download ended early?`

**Comment by sherrillmix** [comment]
Is your internet spotty? It's pretty strange that the download would be failing repeatedly. A [450 error](https://www.serv-u.com/resources/tutorial/431-450-451-452-ftp-response-codes) should mean problems on NCBI's side though. It's strange that it's getting to "100%" on the first download then failing. 

To narrow things down, maybe just call the `getNamesAndNodes()` function directly although presumably that will get you the same result. Running that a second ago produced:

```
> taxonomizr::getNamesAndNodes()
Download status: 1 done; 0 in progress. Total size: 57.70 Mb (100%)... done!             
 [100%] Downloaded 49 bytes...
[1] "./names.dmp" "./nodes.dmp"
```

Could you post the results of sessionInfo() to start narrowing down what could be causing an issue? I notice a "C:/" in your file path so I wonder if this is some fun "feature" of Windows.

**Comment by sxh1136** [comment]
I tried specifying the protocol to http and it seems like its working!

> prepareDatabase('accessionTaxa.sql', protocol = 'http')

Ill do sesseionInfo() after its finished

**Comment by sherrillmix** [comment]
Thanks. Maybe http works better on Windows then (n=1). Still trying to figure out which protocol gives the least hassle.

**Comment by sherrillmix** [comment]
As one more data point, I tried the download on a Windows AWS instance and things seemed to work fine with the default ftp: 

```
> taxonomizr::getNamesAndNodes()
Download status: 1 done; 0 in progress. Total size: 57.70 Mb (100%)... done!             
 [100%] Downloaded 49 bytes...
[1] "./names.dmp" "./nodes.dmp"
Warning message:
In strptime(xx, f, tz = tz) : unable to identify current timezone 'C':
please set environment variable 'TZ'
```

So I guess not all Window installs have problems with FTP.

**Comment by sxh1136** [comment]
My internet connection is fine as far as I can tell. Its running on ethernet I'm able to game and stream easily. 
The same thing happens with getNamesAndNodes()
```
> taxonomizr::getNamesAndNodes()
Download status: 1 done; 0 in progress. Total size: 7.12 Mb (100%)... done!             
Error in resumableDownload(url, tarFile, quiet = FALSE) : 
  Download failed with error: "transfer closed with 53039538 bytes remaining to read". Progress is saved in C:\Users\siufu\AppData\Local\Temp\Rtmpmw218d/taxdump.tar.gz.__TMP__ and continued download can be attempted by repeating the previous command.
Delete C:\Users\siufu\AppData\Local\Temp\Rtmpmw218d/taxdump.tar.gz.__TMP__ or set resume=FALSE to start from scratch.
> taxonomizr::getNamesAndNodes()
Download status: 1 done; 0 in progress. Total size: 9.68 Mb (100%)... done!             
Error in resumableDownload(url, tarFile, quiet = FALSE) : 
  Download failed with error: "transfer closed with 50353138 bytes remaining to read". Progress is saved in C:\Users\siufu\AppData\Local\Temp\Rtmpmw218d/taxdump.tar.gz.__TMP__ and continued download can be attempted by repeating the previous command.
Delete C:\Users\siufu\AppData\Local\Temp\Rtmpmw218d/taxdump.tar.gz.__TMP__ or set resume=FALSE to start from scratch.
> taxonomizr::getNamesAndNodes()
Download status: 1 done; 0 in progress. Total size: 15.12 Mb (100%)... done!             
Error in resumableDownload(url, tarFile, quiet = FALSE) : 
  Download failed with error: "transfer closed with 44648918 bytes remaining to read". Progress is saved in C:\Users\siufu\AppData\Local\Temp\Rtmpmw218d/taxdump.tar.gz.__TMP__ and continued download can be attempted by repeating the previous command.
Delete C:\Users\siufu\AppData\Local\Temp\Rtmpmw218d/taxdump.tar.gz.__TMP__ or set resume=FALSE to start from scratch.
> taxonomizr::getNamesAndNodes()
Download status: 1 done; 0 in progress. Total size: 18.21 Mb (100%)... done!             
Error in resumableDownload(url, tarFile, quiet = FALSE) : 
  Download failed with error: "transfer closed with 41404798 bytes remaining to read". Progress is saved in C:\Users\siufu\AppData\Local\Temp\Rtmpmw218d/taxdump.tar.gz.__TMP__ and continued download can be attempted by repeating the previous command.
Delete C:\Users\siufu\AppData\Local\Temp\Rtmpmw218d/taxdump.tar.gz.__TMP__ or set resume=FALSE to start from scratch.
> taxonomizr::getNamesAndNodes()
Download status: 1 done; 0 in progress. Total size: 28.48 Mb (100%)... done!             
Error in resumableDownload(url, tarFile, quiet = FALSE) : 
  Download failed with error: "transfer closed with 30637484 bytes remaining to read". Progress is saved in C:\Users\siufu\AppData\Local\Temp\Rtmpmw218d/taxdump.tar.gz.__TMP__ and continued download can be attempted by repeating the previous command.
Delete C:\Users\siufu\AppData\Local\Temp\Rtmpmw218d/taxdump.tar.gz.__TMP__ or set resume=FALSE to start from scratch.
> taxonomizr::getNamesAndNodes()
Download status: 1 done; 0 in progress. Total size: 45.72 Mb (100%)... done!             
Error in resumableDownload(url, tarFile, quiet = FALSE) : 
  Download failed with error: "transfer closed with 12568524 bytes remaining to read". Progress is saved in C:\Users\siufu\AppData\Local\Temp\Rtmpmw218d/taxdump.tar.gz.__TMP__ and continued download can be attempted by repeating the previous command.
Delete C:\Users\siufu\AppData\Local\Temp\Rtmpmw218d/taxdump.tar.gz.__TMP__ or set resume=FALSE to start from scratch.
> taxonomizr::getNamesAndNodes()
Download status: 1 done; 0 in progress. Total size: 57.70 Mb (100%)... done!             
Error in resumableDownload(url, tarFile, quiet = FALSE) : 
  Download failed with error: "server did not report OK, got 450". Progress is saved in C:\Users\siufu\AppData\Local\Temp\Rtmpmw218d/taxdump.tar.gz.__TMP__ and continued download can be attempted by repeating the previous command.
Delete C:\Users\siufu\AppData\Local\Temp\Rtmpmw218d/taxdump.tar.gz.__TMP__ or set resume=FALSE to start from scratch.
> taxonomizr::getNamesAndNodes()
Download status: 1 done; 0 in progress. Total size: 57.70 Mb (100%)... done!             
Error in taxonomizr::getNamesAndNodes() : 
  Downloaded file does not match ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz File corrupted or download ended early?
```
```
> sessionInfo() 
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] taxonomizr_0.10.3

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.8        compiler_4.0.2    R.methodsS3_1.8.1 R.utils_2.10.1   
 [5] prettyunits_1.1.1 remotes_2.2.0     tools_4.0.2       bit_4.0.5        
 [9] testthat_2.3.2    digest_0.6.25     pkgbuild_1.1.0    pkgload_1.1.0    
[13] RSQLite_2.2.12    memoise_1.1.0     lifecycle_0.2.0   gtable_0.3.0     
[17] pkgconfig_2.0.3   rlang_1.0.6       DBI_1.1.0         cli_2.0.2        
[21] rstudioapi_0.11   curl_5.0.0        xfun_0.27         withr_2.3.0      
[25] vctrs_0.3.4       desc_1.2.0        fs_1.5.0          devtools_2.3.2   
[29] bit64_4.0.5       rprojroot_1.3-2   grid_4.0.2        data.table_1.13.0
[33] glue_1.6.2        R6_2.4.1          processx_3.4.4    fansi_0.4.1      
[37] sessioninfo_1.1.1 blob_1.2.3        callr_3.4.4       purrr_0.3.4      
[41] magrittr_1.5      backports_1.1.10  ps_1.3.4          ellipsis_0.3.1   
[45] usethis_2.0.0     assertthat_0.2.1  tinytex_0.34      crayon_1.3.4     
[49] R.oo_1.24.0      
```

**Comment by sherrillmix** [comment]
That certainly is giving you a large hassle to download. And then failing to download the complete file once it actually does complete. Definitely something major going wrong there. You said setting protocol to http works for you though? Assuming http does work, I think my answer might be to use http and kick the ftp can up to the `curl` package. 

If you were motivated to help debug though, I'd be curious to see if `curl::multi_download('ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz','tmp.tmp')` ends up with the same errors (taking taxonomizr code completely out of the mix).

For comparison, when I run that command I get a clean download:

```
> curl::multi_download('ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz','tmp.tmp')
Download status: 1 done; 0 in progress. Total size: 57.71 Mb (100%)... done!             
  success status_code resumefrom
1    TRUE         226          0
                                                 url destfile error type
1 ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz  tmp.tmp  <NA> <NA>
             modified     time
1 2023-02-22 07:28:33 3.251277
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   headers
1 220-,  This warning banner provides privacy and security notices consistent with ,  applicable federal laws, directives, and other federal guidance for accessing ,  this Government system, which includes all devices/storage media attached to ,  this system. This system is provided for Government-authorized use only. ,  Unauthorized or improper use of this system is prohibited and may result in ,  disciplinary action and/or civil and criminal penalties. At any time, and for ,  any lawful Government purpose, the government may monitor, record, and audit ,  your system usage and/or intercept, search and seize any communication or data ,  transiting or stored on this system. Therefore, you have no reasonable ,  expectation of privacy. Any communication or data transiting or stored on this ,  system may be disclosed or used for any lawful Government purpose., 220 FTP Server ready., 331 Anonymous login ok, send your complete email address as your password, 230 Anonymous access granted, restrictions apply, 257 "/" is the current directory, 250 CWD command successful, 250 CWD command successful, 213 20230222122833, 229 Entering Extended Passive Mode (|||50359|), 200 Type set to I, 213 60514091, 150 Opening BINARY mode data connection for taxdump.tar.gz (60514091 bytes), 226 Transfer complete
```

**Comment by sherrillmix** [comment]
I added some additional messages output on download to v0.10.04 (on github but not CRAN currently) for these types of situations. Here, I guess as long as `protocol='http'` is doing it for you then I'll mark this closed. Let me know if anything further arises and good luck in your research.
