### ISSUE TITLE
prepareDatabase('accessionTaxa.sql')  downloading names and nodes with getnamesandnodes() error:

### ISSUE THREAD

**Issue by xuxia10** [sherrillmix/taxonomizr#58]
Hi, I made a error. 
prepareDatabase('accessionTaxa.sql')
Downloading names and nodes with getNamesAndNodes()
Error: 'multi_download' is not an exported object from 'namespace:curl'
My version is r-taxonomizr              0.10.2            r42h133d619_0

**Comment by sherrillmix** [comment]
It sounds like you might have an older version of the `curl` package. That should have been updated when you installed `taxonomizr` but something funny may have happened. Perhaps you were in an R session and updated `curl` while installing taxonomizr and that didn't update the currently running session? Could you try restarting R and if that doesn't fix things could you report the output of `library('taxonomizr');sessionInfo()` so we can check package versions.

**Comment by xuxia10** [comment]
I restared R, but I didn't fix the error;
package versions:
locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] taxonomizr_0.10.2

loaded via a namespace (and not attached):
[1] compiler_4.2.2    data.table_1.14.8

**Comment by sherrillmix** [comment]
Oops I thought curl would get loaded when taxonomizr was loaded but looks like that's not the case (changed in newer versions of R or I'm just misremembering?). Could you run the command that gave you the error then do `sessionInfo()`? We're largely looking for the curl version so if you don't see it listed after that you could also do `library('curl');sessionInfo()` or `packageVersion('curl')` to check just that aspect. And I didn't see the session info for OS in the above. Are you on Linux, Windows or Mac?

**Comment by xuxia10** [comment]
I added the object, but I haven't encountered the same error yet. This is the added version：
R version 4.2.2 (2022-10-31)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Ubuntu 22.04.1 LTS

Matrix products: default
BLAS/LAPACK: /s1/xuxia/miniconda3/envs/virus/lib/libopenblasp-r0.3.21.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] curl_4.3.3        taxonomizr_0.10.2

loaded via a namespace (and not attached):
[1] compiler_4.2.2    data.table_1.14.8

**Comment by sherrillmix** [comment]
It sure seems like it's that older version of `curl` that's causing the trouble. I thought that  should have been updated automatically when installing `taxonomizr` but apparently wasn't. Do you remember how you installed? And a fix might be to just update manually:
`install.packages('curl')` 
The end results should be `curl` package version 0.5.0 (or greater).

**Comment by xuxia10** [comment]
yes, after I updated the version, the previous problem was solved and the error:
Error in resumableDownload(url, tarFile, quiet = FALSE) : 
  Download failed with error: "transfer closed with 57740454 bytes remaining to read". Progress is saved in /tmp/RtmpTyV1HZ/taxdump.tar.gz.__TMP__ and continued download can be attempted by repeating the previous command.
Delete /tmp/RtmpTyV1HZ/taxdump.tar.gz.__TMP__ or set resume=FALSE to start from scratch.
Calls: prepareDatabase -> do.call -> <Anonymous> -> resumableDownload
Execution halted

R version 4.2.2 (2022-10-31)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Ubuntu 22.04.1 LTS

Matrix products: default
BLAS/LAPACK: /s1/xuxia/miniconda3/envs/virus/lib/libopenblasp-r0.3.21.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] taxonomizr_0.10.2

loaded via a namespace (and not attached):
[1] compiler_4.2.2    curl_5.0.0        data.table_1.14.8

**Comment by sherrillmix** [comment]
That's good one error is out of the way. The new error sounds suspiciously similar to an error reported in #57. That seemed to have been caused with some sort of issue with ftp downloads. Could you try `prepareDatabase(protocol='http')` to attempt to download with http instead. If that fixes things then perhaps it's time to for me switch the default protocol to http (although weird that there would be issues arising from what should be a pretty standard transfer with ftp or http).

**Comment by sherrillmix** [comment]
I'm going to close this but feel free to reopen or start a new issue if there's any additional problems. Good luck with your research.

**Comment by xuxia10** [comment]
yes, resolved
