### ISSUE TITLE
Error:database is locked with prepareDatabase

### ISSUE THREAD

**Issue by sarah-buddle** [sherrillmix/taxonomizr#59]
Hi, I'm getting the following error message when trying to run prepareDatabase:

```
>prepareDatabase(getAccessions=FALSE)
Downloading names and nodes with getNamesAndNodes()
Download status: 1 done; 0 in progress. Total size: 57.81 Mb (100%)... done!             
Preprocessing names with read.names.sql()
Error: database is locked
In addition: Warning message:
Couldn't set synchronous mode: database is locked
Use `synchronous` = NULL to turn off this warning. 
```

It seems to be downloading the nodes.dmp and names.dmp files, but the sqlite file is empty. I've also tried running with those files downloaded separately from NCBI, and with http since that seems to have helped some other people, but I'm getting the same message. Do you know what could be going wrong here?

**Comment by sherrillmix** [comment]
That sounds like either a permissions issue in accessing/writing to the sqlite database or something related to multiple processes trying to write to the same database (probably not a download problem).

 You said you saw a (empty) sqlite file so it seems a database file was created and so simple file permission problems seem less likely. Any chance a previous run stopped midway and left a lock on the database? If you remove the sqlite file and repeat do you get the same error?

**Comment by sarah-buddle** [comment]
Yes I think you're right - a clean install in a different directory worked. Sorry for the simple question - I had tried that last week and it had failed for a different reason but all seems to be working now. Thanks for your help and for the very useful package!

**Comment by sherrillmix** [comment]
No problem at all. That's definitely not the clearest error messages from SQLite so I'm glad to have it documented if someone else runs into it. Thanks for the bug report and good luck with your research!
