### ISSUE TITLE
Pointing R to an already prepared database

### ISSUE THREAD

**Issue by jkimsis** [sherrillmix/taxonomizr#61]
Hello,

is there a way to point R to a taxonomizr database that has been prepared before? For some reason running R from a terminal (where I prepared the database) works fine, but R studio doesn't recognise the database.

Edit: actually changing the working directory in the terminal where the database was prepared also breaks it: accessionTaxa.sql does not exist.

**Comment by sherrillmix** [comment]
It'd help to see the code you're running and error you're generating. But as a first guess, perhaps it's a working directory/path issue? So maybe try specifying the whole path in R studio e.g. `/home/jkimsis/DIRECTORY/WHERE/DATABASE/IS/DATABASE.SQL`?

**Comment by jkimsis** [comment]
Giving the full path does work from terminal and R studio. Is this the intended functionality or is there some kind of path variable in R I can add it to so it persists after a restart?

**Comment by sherrillmix** [comment]
That's in the realm of basic path handling in R e.g. random google hit:
https://bookdown.org/ndphillips/YaRrr/the-working-directory.html
Base R started from terminal automatically sets the working directory to wherever you were in terminal. RStudio is usually started as a global shortcut so starts in some general directory e.g. `/home/jkimsis`. One solution might be to add `setwd('/PATH/TO/DIRECTORY/YOU/WANT')` at the start of your script.

**Comment by sherrillmix** [comment]
I'm going to close but feel free to reopen/start a new issue if you run into any more problems. Good luck with your research!
