### ISSUE TITLE
error in prepareDatabase

### ISSUE THREAD

**Issue by babinecha** [sherrillmix/taxonomizr#65]
Hi! I'm trying to use the package, but the following error has appeared when the download has finish:

Error in resumableDownload(url, tarFile, resume = resume) : 
  Download failed with error: "server did not report OK, got 450". Progress is saved in C:\Users\barba\AppData\Local\Temp\RtmpqwD05J/taxdump.tar.gz.__TMP__ and continued download can be attempted by repeating the previous command.

when I try to repeat the command getNamesAndNodes(), the following error appears:

Error in getNamesAndNodes() : 
  Downloaded file does not match ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz File corrupted or download ended early?
Local: c96d49cb56a76c50ba2174cae2836b47
Remote: 65d9fdccda386408a89171f039d59c12

What is hapening? What can I do?

Thanks

**Comment by sherrillmix** [comment]
That should indicate something is going wrong with the download. I just tried `getNamesAndNodes()` and it completed without error so if it was a problem with NCBI servers then it was a short term or localized hiccup. 

I think next steps for you might be to try again just to make sure it wasn't a blip. Then maybe try on another network if there's any chance your internet could be doing something funny. If that doesn't fix things let me know your `sessionInfo()` just so we're on the same page with versions/OS. Could also try:
`getNamesAndNodes(protocol='http')`
to see if it's ftp (the default) related. Worst case you could just download manually from:
http://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz

**Comment by babinecha** [comment]
Hi! Thanks for response!

I already tried several times and the problem persisted.
Then, I followed de tips of error #57 and error #12 and tried:

`prepareDatabase('accessionTaxa.sql',types = c("nucl_gb", "nucl_wgs"), protocol='http')`

It worked that way!

thanks again

**Comment by sherrillmix** [comment]
Hmm so it could have been an ftp vs http issue. It's hard to track down which protocol is less of a pain. Glad it worked out. Good luck with your research!
