### ISSUE TITLE
Error in prepareDatabase('accessionTaxa.sql'), change in url?

### ISSUE THREAD

**Issue by mgpapadaki** [sherrillmix/taxonomizr#66]
Hello,

I've been trying to follow the instructions to set up the database using the prepareDatabase('accessionTaxa.sql') command. I encounter the following issue: 

```
> prepareDatabase('accessionTaxa.sql')
Downloading names and nodes with getNamesAndNodes()
Download status: 1 done; 0 in progress. Total size: 0 b ... done!             
Error in resumableDownload(url, tarFile, resume = resume) : 
  Download failed with error: "Could not resolve host: ftp.ncbi.nih.gov".
```
I have tried manually checking the ftp url and it seems like it has changed to ftp.ncbi.nlm.nih.gov. The older url seems hard coded into the prepareDatabase function and I was wondering if you could help me solve this issue. 

Thank you very much in advance!

**Comment by sherrillmix** [comment]
Both http://ftp.ncbi.nih.gov/ or ftp://ftp.ncbi.nih.gov seem to work fine for me. And the url isn't hardcoded but is accessible with the `url=` argument. Perhaps a transient problem with NCBI or some funny internet connections?

**Comment by sherrillmix** [comment]
Closing but let me know if problem persists/pops up again.

**Comment by mgpapadaki** [comment]
Thank you very much for your reply. I was able to make it work for me by using the following:
`prepareDatabase('accessionTaxa.sql',url= 'https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz')`
