### ISSUE TITLE
sql table failed to generate and I can't delete it to try again

### ISSUE THREAD

**Issue by maxfarrell** [sherrillmix/taxonomizr#68]
I got the error: `Error: no such table: accessionTaxa` so am trying to re-download the database. However, R seems to think it already exists. I deleted the source files in my tmpDir, but I can't seem to locate the .sql file (it's not in my set tmpDir), so I'm stuck.

Any advice on removing the .sql file so I can start again?

**Comment by sherrillmix** [comment]
You might need to provide a bit more detail, e.g. the exact commands and output you are running, but if I'm understanding things correctly the .sql file should be whatever you set as the first `sqlFile` argument to `prepareDatabase()` so `XXX.sql` in `prepapreDatase('XXX.sql')` or `nameNode.sqlite` by default. That'll be in your working directory (`getwd()`) by default.

**Comment by maxfarrell** [comment]
Hi - apologies for the lack of detail before. 

I had trouble with the default call  `prepareDatabase('accessionTaxa.sql')` so ammended it to use a local temp directory, and use the http protocol: `prepareDatabase('accessionTaxa.sql', tmpDir = "../intermediate/", resume=TRUE, protocol='http')`

Unfortunately the 'accessionTaxa.sql' object wasn't in my working directory after I made the first attepmt, hence my issue. 

I'm now attempting to re-download the database by calling it 'accessionTaxa2.sql' and it is currently re-downloading, but if you have any other insights as to why the earlier error came up, I'd be glad to hear it.

**Comment by sherrillmix** [comment]
That does seem weird. Perhaps some sort of directory mismatch? Hopefully it's working for you now. I'm going to close issue but feel free to reopen if still a problem.
