### ISSUE TITLE
extraSqlCommand not working for me

### ISSUE THREAD

**Issue by cristinagalisteo** [sherrillmix/taxonomizr#69]
Hi! 

I've been having troubles preparing the database. My machine has most programs (including R) installed in a smaller disk (42 Gb free) and the data information is saved in a bigger one (4.5 T free). Logically, I want to save the database in the 4.5T one. 

Thus, I'd try to set the database manually: 

```
getNamesAndNodes()
getAccession2taxid(types='prot')

read.names.sql('names.dmp','accessionTaxa.sql')
read.nodes.sql('nodes.dmp','accessionTaxa.sql')
```

This part is all good. But `read.accession2taxid()` command save temporary (I think?) info in my small disk which, as you could see, does not have enough space. 

I have tried changing the `straSqlCommand` :

```
read.accession2taxid(list.files('.','accession2taxid.gz$'),'mypath/accessionTaxa.sql', 
                     extraSqlCommand = "PRAGMA temp_store_directory = 'mypath'" )
# and: 
read.accession2taxid(list.files('.','accession2taxid.gz$'),'mypath/accessionTaxa.sql', 
                     extraSqlCommand = "pragma temp_store = 2;" )
```
My machine has > 100GB RAM so I think I'm good. 

None of these options are working for me. I not sure what I am doing wrong. 

Thank you!

**Comment by sherrillmix** [comment]
Related to #5, #41 and #52 probably. Temp directories and R and sqlite definitely don't like to play nicely together. 

Those pragma look right but I see `temp_store_directory` is [deprecated](https://www.sqlite.org/pragma.html#pragma_temp_store_directory) (and it was only "advisory" anyway with some OS apparently ignoring).  Maybe starting R with the TMPDIR redefined with `TMPDIR=/path/to/tmp R` or `SQLITE_TMPDIR=/path/to/tmp R` (the prepended variable assignment is the important bit) would convince sqlite to listen to your path?

If that doesn't fix it, can I see the actual commands (with paths censored if desired) and outputs/errors? And maybe  `sessionInfo()`.

**Comment by cristinagalisteo** [comment]
I redefined the temporal directory as you indicated and worked perfectly. Thank you so much for your quick answer!

**Comment by sherrillmix** [comment]
Great. Glad it worked. It's surprisingly difficult to get sqlite temp files where you want them. Good luck with your research.
