### ISSUE TITLE
Memory Required?

### ISSUE THREAD

**Issue by chasemc** [sherrillmix/taxonomizr#7]
What machine specs are required to run this package?  I had a little over 30GB left on my hard drive and got an out of memory error at this step in the vignette :
https://github.com/sherrillmix/taxonomizr/blob/master/vignettes/usage.Rmd#convert-accessions-to-database
`read.accession2taxid(list.files('.','accession2taxid.gz$'),'accessionTaxa.sql')`

there was a >16 GB temp file after the error as well.

**Comment by chasemc** [comment]
This package downloads the NCBI datasets and creates the sql databases **into your working directory**. In my case this was in a git-controlled environment.

**Comment by chasemc** [comment]
In case someone else happens upon this. You will wind up using a little over 35 GB of hard drive space, with ~13 GB tied up in temp files until R is closed (that part may vary)

**Comment by sherrillmix** [comment]
Thanks chasemc. I should add that to the readme.
